version: 0.2
env:
  parameter-store:
        FOD_RELEASE_ID: "/fod/releaseid"
        FOD_TENANT: "/fod/tenant"
        FOD_USER: "/fod/user"
        FOD_PAT: "/fod/pat"
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      - mvn clean
  build:
    commands:
      - mvn -Pwar clean package
      #- mvn package
  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN in template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
      ###############################################################
      #                 INTEGRATE FORTIFY SAST                      #
      #                                                             #
      # For FORTIFY ON DEMAND uncomment the next line               #
      - bash devops-integrations/aws/fortify-sast-fod.bash
      #                                                             #
      # For FORTIFY SCANCENTRAL uncomment the next line             #
      #- bash devops-integrations/aws/fortify_sast_scancentral.bash             
      #                                                             #
      #                                                             #
      ###############################################################      
artifacts:
  files:
    - 'appspec.yml'
    - 'template.yml'
    - 'scripts/*'
    - 'target/iwa.war'
    - 'template-configuration.json'
